version: '3.8'
services:
  client:
    build:
      context: ./FE
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./BE
    ports:
      - '3002:3002'
    depends_on:
      - mongo
    environment:
      SALT_ROUNDS: some_key
      JWT_SECRET: tungnq
      MONGO_URI: mongodb://admin:pass@mongo:27017/?authMechanism=DEFAULT
      ACCESS_TOKEN_SECRET: tungnguyenquoc
      PORT: 3002

  mongo:
    image: mongo #latest version
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - './mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
# docker-compose up --build --detach
