# version: '3.8'

# services:
#   mongo:
#     image: mongo #latest version
#     container_name: mongo-container
#     ports:
#       - 27017:27017
#     volumes:
#       - './mongodb:/data/db'
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: pass

#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express-container
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#       ME_CONFIG_MONGODB_ADMINPASSWORD: pass
#       ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
#docker-compose -f mongo-compose.yml up --detach
#docker-compose -f mongo-compose.yml down
#mongosh "mongodb://root:Abc123456789@localhost:27018" --username root --authenticationDatabase admin
#sample data is here:
#https://atlas-education.s3.amazonaws.com/sampledata.archive

#access to mongo-container's terminal
#cd C:\Users\sunli\Documents\code\YoutubeChannel\2023\MongoDBTutorialsForBeginners2023\myapp
#docker exec -it mongo-container bash
#Connect inside container:
#mongosh "mongodb://root:Abc123456789@localhost:27017" --username root --authenticationDatabase admin
#use sample_mflix
#Download and restore data
#curl https://atlas-education.s3.amazonaws.com/sampledata.archive -o sampledata.archive
#mongorestore --username root --password Abc123456789 --authenticationDatabase admin --archive=./sampledata.archive
